frameworkVersion: ">=3.38.0 <4.0.0"

service: token-service

provider:
  name: aws
  ecr:
    images:
      okdata-token-service:
        path: ./
        platform: linux/amd64
  region: ${opt:region, 'eu-west-1'}
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:custom.deploymentBucket.${self:provider.stage}, self:custom.deploymentBucket.dev}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  logRetentionInDays: 90
  tracing:
    lambda: true
    apiGateway: true
  environment:
    GIT_REV: ${git:branch}:${git:sha1}
    KEYCLOAK_SERVER: ${ssm:/dataplatform/shared/keycloak-server-url}
    KEYCLOAK_REALM: api-catalog
    CLIENT_ID: token-service
    SERVICE_NAME: token-service
  iam:
    role:
      permissionsBoundary: "arn:aws:iam::${aws:accountId}:policy/oslokommune/oslokommune-boundary"
      managedPolicies:
        - 'arn:aws:iam::${aws:accountId}:policy/token-service-policy'
        - 'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess'
  tags:
    GIT_REV: ${git:branch}:${git:sha1}

functions:
  create-user-token: ${file(serverless/functions/create-user-token.yml)}
  refresh-user-token: ${file(serverless/functions/refresh-user-token.yml)}
  create-client-token: ${file(serverless/functions/create-client-token.yml)}
  refresh-client-token: ${file(serverless/functions/refresh-client-token.yml)}

plugins:
  - serverless-better-credentials # must be first
  - "@kakkuk/serverless-aws-apigateway-documentation"
  - serverless-plugin-git-variables
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3
  documentation: ${file(serverless/documentation/documentation.yml)}
  deploymentBucket:
    prod: ok-origo-dataplatform-config-prod
    dev: ok-origo-dataplatform-config-dev
