openapi: "3.0.1"
info:
  title: "dev-token-service"
  version: "2019-09-26T07:29:19Z"
servers:
- url: "https://***REMOVED***.execute-api.eu-west-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/dev"
paths:
  /token:
    post:
      description: "Creates and returns an access token."
      requestBody:
        description: "User credentials."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createTokenRequest"
        required: true
      responses:
        400:
          description: "400 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/standardResponse"
        401:
          description: "401 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/unauthorizedResponse"
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/createTokenResponse"
components:
  schemas:
    unauthorizedResponse:
      required:
      - "error_description"
      type: "object"
      properties:
        error_description:
          type: "string"
        error:
          type: "string"
    createTokenResponse:
      required:
      - "access_token"
      - "expires_in"
      - "not-before-policy"
      - "refresh_expires_in"
      - "refresh_token"
      - "scope"
      - "session_state"
      - "token_type"
      type: "object"
      properties:
        access_token:
          type: "string"
        refresh_token:
          type: "string"
        refresh_expires_in:
          type: "integer"
        not-before-policy:
          type: "integer"
        scope:
          type: "string"
        token_type:
          type: "string"
        session_state:
          type: "string"
        expires_in:
          type: "integer"
    standardResponse:
      title: "Standard Response"
      required:
      - "message"
      type: "object"
      properties:
        message:
          type: "string"
    createTokenRequest:
      required:
      - "password"
      - "username"
      type: "object"
      properties:
        password:
          type: "string"
        username:
          type: "string"
